<?php 

define('CONST_MESSAGE_REGISTER',1001);
define('CONST_MESSAGE_LOGIN',1002);
define('CONST_MESSAGE_CREATE_ROLE',1003);
define('CONST_MESSAGE_GET_ROLE',1004);
define('CONST_MESSAGE_LIST_ROOM',1005);
